@baseUrl = http://localhost:3333


# @name create_user

POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Gustavinhooo",
  "email": "email@email.com",
  "password": "123456"
}

###

POST {{baseUrl}}/session
Content-Type: application/json

{
  "name": "Gustavinhooo",
  "email": "email@email.com",
  "password": "123456"
}